# Generated by Django 4.2 on 2025-06-04 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de eliminacion')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado')),
                ('name', models.CharField(help_text='Nombre de Area', max_length=250, verbose_name='Nombre')),
                ('description', models.CharField(help_text='Descripción de Área', max_length=250, null=True, verbose_name='Descripción')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to='employees.employee', verbose_name='Usuario creador')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to='employees.employee')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Área',
                'ordering': ('created_at',),
            },
        ),
    ]
