# Generated by Django 4.2 on 2025-06-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_concept_options_type_marking_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_marking',
            name='name',
            field=models.CharField(help_text='Nombre de tipo de marcación', max_length=200, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='type_marking',
            name='description',
            field=models.CharField(help_text='Descripción de tipo de marcación', max_length=200, null=True, unique=True, verbose_name='Descripción'),
        ),
    ]
