# Generated by Django 4.2 on 2025-06-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_type_marking_name_alter_type_marking_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
