# Generated by Django 4.2 on 2025-06-25 02:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_area_employee_position'),
        ('maintenance', '0005_delete_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_marking',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción de tipo de marcación', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='Type_justificaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de eliminacion')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado')),
                ('name', models.CharField(help_text='Nombre de tipo de justificación', max_length=200, null=True, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, help_text='Descripción de tipo de justificación', max_length=200, null=True, verbose_name='Descripción')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to='employees.employee', verbose_name='Usuario creador')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to='employees.employee')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Tipo de justificación',
                'verbose_name_plural': 'Tipo de justificaciones',
                'ordering': ('created_at',),
            },
        ),
    ]
