# Generated by Django 4.2 on 2025-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_hours_worked'),
        ('employees', '0002_employee_area_employee_position'),
        ('maintenance', '0006_alter_type_marking_description_type_justificaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_justificaction',
            new_name='Type_justification',
        ),
        migrations.AlterField(
            model_name='position',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Salario Base'),
        ),
    ]
