# Generated by Django 4.2 on 2025-07-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_rename_type_justificaction_type_justification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción de concepto de nómina', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='type',
            field=models.CharField(choices=[('base', 'Concepto Base'), ('descuento', 'Concepto de Descuento'), ('auxiliar', 'Concepto Auxiliar')], default='base', max_length=30, verbose_name='Tipo'),
        ),
    ]
