# Generated by Django 4.2 on 2025-06-17 23:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Detail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de eliminacion')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado')),
                ('start_date', models.DateField(help_text='Fecha de Inicio de Vigencia', verbose_name='Fecha de Inicio de Vigencia')),
                ('end_date', models.DateField(help_text='Fecha de Fin de Vigencia', verbose_name='Fecha de Fin de Vigencia')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to='employees.employee', verbose_name='Usuario creador')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to='employees.employee')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Empleado', to='employees.employee', verbose_name='Empleado')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to='employees.employee')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Horario', to='schedule.schedule', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Detalle de Horario',
                'verbose_name_plural': 'Detalles de Horarios',
                'ordering': ('created_at',),
            },
        ),
    ]
