# Generated by Django 4.2 on 2025-06-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='break_time',
            field=models.DurationField(blank=True, help_text='Duración del receso (ej: 1 hora)', null=True, verbose_name='Tiempo de receso'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tolerance',
            field=models.DurationField(blank=True, help_text='Tiempo de tolerancia al ingreso (ej: 5 minutos)', null=True, verbose_name='Tolerancia'),
        ),
    ]
