# Generated by Django 4.2 on 2025-06-24 01:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_area_employee_position'),
        ('maintenance', '0005_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de eliminacion')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(help_text='Fecha de Registro de Asistencia', verbose_name='Fecha de Registro')),
                ('hours_worked', models.IntegerField(blank=True, null=True, verbose_name='Horas Trabajadas')),
                ('state', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completado', 'Completado')], default=None, max_length=30, null=True, verbose_name='Estado')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to='employees.employee', verbose_name='Usuario creador')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to='employees.employee')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado_attendance', to='employees.employee', verbose_name='Empleado')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceMarking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de eliminacion')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hour', models.TimeField(blank=True, null=True, verbose_name='Hora de marcación')),
                ('observation', models.CharField(help_text='Detallar si existe alguna observación', null=True, verbose_name='Observaciones')),
                ('state', models.CharField(blank=True, choices=[('Puntual', 'Puntual'), ('Tardanza', 'Tardanza')], default=None, max_length=30, null=True, verbose_name='Estado')),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asistencia', to='attendance.attendance', verbose_name='Asistencia')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to='employees.employee', verbose_name='Usuario creador')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to='employees.employee')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to='employees.employee')),
                ('type_marking', models.ForeignKey(help_text='Establecer el tipo de marcación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_marcacion', to='maintenance.type_marking', verbose_name='Tipo de Marcación')),
            ],
            options={
                'verbose_name': 'Marcación',
                'verbose_name_plural': 'Marcaciones',
                'ordering': ('created_at',),
            },
        ),
    ]
