# Generated by Django 4.2 on 2025-06-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='state',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completado', 'Completado')], default='Pendiente', max_length=30, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='attendancemarking',
            name='observation',
            field=models.CharField(blank=True, help_text='Detallar si existe alguna observación', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='attendancemarking',
            name='state',
            field=models.CharField(blank=True, choices=[('Antes de tiempo', 'Antes de tiempo'), ('A tiempo', 'A tiempo'), ('Tardanza', 'Tardanza')], default=None, max_length=30, null=True, verbose_name='Estado'),
        ),
    ]
