# Generated by Django 4.2 on 2025-06-25 02:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_area_employee_position'),
        ('attendance', '0003_alter_attendance_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='state',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completado', 'Completado'), ('Justificado', 'Justificado')], default='Pendiente', max_length=30, null=True, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de eliminacion')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('reason', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Motivo')),
                ('justification', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Justificación')),
                ('justification_file', models.FileField(blank=True, help_text='Evidencias', null=True, upload_to='attendence/templates', verbose_name='Documento de Justificación')),
                ('state', models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Pendiente'), ('Pendiente', 'Pendiente')], default=None, max_length=30, null=True, verbose_name='Estado')),
                ('attedance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attedance_justification', to='attendance.attendance', verbose_name='Asistencia_Justificacion')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to='employees.employee', verbose_name='Usuario creador')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to='employees.employee')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Justificacion',
                'verbose_name_plural': 'Justificaciones',
                'ordering': ('created_at',),
            },
        ),
    ]
