# Generated by Django 4.2 on 2025-06-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_type_marking_description_type_justificaction'),
        ('attendance', '0004_alter_attendance_state_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='type',
            field=models.ForeignKey(help_text='Establecer el tipo de justificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_justificacion', to='maintenance.type_justificaction', verbose_name='Tipo de Justificación'),
        ),
    ]
