# Generated by Django 4.2 on 2025-06-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_justification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Horas Trabajadas'),
        ),
    ]
