# Generated by Django 4.2 on 2025-06-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemarking',
            name='state',
            field=models.CharField(blank=True, choices=[('Antes de tiempo', 'Antes de tiempo'), ('A tiempo', 'A tiempo'), ('Tardanza', 'Tardanza'), ('Receso', 'Receso')], default=None, max_length=30, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='justification',
            name='state',
            field=models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default=None, max_length=30, null=True, verbose_name='Estado'),
        ),
    ]
