# Generated by Django 4.2 on 2025-07-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancemarking_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Horas extra'),
        ),
    ]
