# Generated by Django 4.2 on 2025-12-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemarking',
            name='observation',
            field=models.CharField(blank=True, help_text='Detallar si existe alguna observación', max_length=500, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='attendancemarking',
            name='state',
            field=models.CharField(blank=True, choices=[('Antes de tiempo', 'Antes de tiempo'), ('A tiempo', 'A tiempo'), ('Fuera de tiempo', 'Fuera de tiempo'), ('No determinado', 'No determinado')], default=None, max_length=30, null=True, verbose_name='Estado'),
        ),
    ]
