# Generated by Django 4.2 on 2025-06-04 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de eliminacion')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado')),
                ('description', models.CharField(help_text='Descripción de la Nómina', max_length=250, null=True, verbose_name='Descripción')),
                ('year', models.CharField(help_text='Año de aplicación para la planificación registrada', max_length=4, verbose_name='Ejercicio')),
                ('month', models.CharField(blank=True, choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default=None, max_length=30, null=True, verbose_name='Mes')),
                ('total_amount_services', models.DecimalField(decimal_places=20, default=0, max_digits=30, verbose_name='Monto total por servicios')),
                ('total_amount', models.DecimalField(decimal_places=20, default=0, max_digits=30, verbose_name='Monto Total')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to='employees.employee', verbose_name='Usuario creador')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to='employees.employee')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nómina',
                'ordering': ('created_at',),
            },
        ),
    ]
