# Generated by Django 4.2 on 2025-06-17 21:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_delete_schedule'),
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de eliminacion')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado')),
                ('days_worked', models.IntegerField(blank=True, null=True, verbose_name='Total de días laborados')),
                ('total_hours', models.DecimalField(decimal_places=20, default=0, max_digits=30, verbose_name='Total de horas laboradas')),
                ('total_remuneration', models.DecimalField(decimal_places=20, default=0, max_digits=30, verbose_name='Total remuneración')),
                ('total_discounts', models.DecimalField(decimal_places=20, default=0, max_digits=30, verbose_name='Total de descuentos')),
                ('net_total', models.DecimalField(decimal_places=20, default=0, max_digits=30, verbose_name='Total neto')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to='employees.employee', verbose_name='Usuario creador')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to='employees.employee')),
                ('employee', models.ForeignKey(help_text='Código y nombre del empleado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_employee', to='employees.employee', verbose_name='Empleado')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to='employees.employee')),
                ('payroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nomina', to='payroll.payroll', verbose_name='Nomina')),
            ],
            options={
                'verbose_name': 'Nomina Empleado',
                'verbose_name_plural': 'Nominas Empleados',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PayrrollEmployeeDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de eliminacion')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado')),
                ('calculated_amount', models.DecimalField(decimal_places=20, default=0, max_digits=30, verbose_name='Monto calculado')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.concept', verbose_name='Concepto')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to='employees.employee', verbose_name='Usuario creador')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to='employees.employee')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to='employees.employee')),
                ('payroll_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nomina_Empleado', to='payroll.payrollemployee', verbose_name='Nomina Empleado')),
            ],
            options={
                'verbose_name': 'Concepto nómina',
                'verbose_name_plural': 'Conceptos nómina',
                'ordering': ('created_at',),
            },
        ),
    ]
