# Generated by Django 4.2 on 2025-06-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollemployee_payrrollemployeedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='total_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_amount_services',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, verbose_name='Monto total por servicios'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='net_total',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, verbose_name='Total neto'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='total_discounts',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, verbose_name='Total de descuentos'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='total_hours',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, verbose_name='Total de horas laboradas'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='total_remuneration',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, verbose_name='Total remuneración'),
        ),
        migrations.AlterField(
            model_name='payrrollemployeedetail',
            name='calculated_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, verbose_name='Monto calculado'),
        ),
    ]
