# Generated by Django 4.2 on 2025-06-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payroll_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default=None, max_length=30, null=True, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='state',
            field=models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default=None, max_length=30, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=30, null=True, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_amount_services',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=30, null=True, verbose_name='Monto total por servicios'),
        ),
    ]
