# Generated by Django 4.2 on 2025-07-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payroll_month_alter_payroll_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='state',
            field=models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('En revisión', 'En Revisión')], default=None, max_length=30, null=True, verbose_name='Estado'),
        ),
    ]
