# Generated by Django 4.2 on 2025-07-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_payroll_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='faults',
            field=models.IntegerField(blank=True, null=True, verbose_name='Faltas'),
        ),
    ]
