# Generated by Django 4.2 on 2025-07-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payrollemployee_faults'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Horas extra laboradas'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='net_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30, verbose_name='Total neto'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='total_discounts',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30, verbose_name='Total de descuentos'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Total de horas laboradas'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='total_remuneration',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30, verbose_name='Total remuneración'),
        ),
    ]
