# Generated by Django 4.2 on 2025-07-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payrollemployee_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='total_amount_services',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30, verbose_name='Total aportes empleador'),
        ),
    ]
