# Generated by Django 4.2 on 2025-06-04 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de eliminacion')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado')),
                ('document_type', models.CharField(blank=True, choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default=None, max_length=30, null=True, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=10, verbose_name='Código')),
                ('profile_picture', models.FileField(blank=True, help_text='Subir la imagen (jpg,jpge, png)', null=True, upload_to='employee/templates', verbose_name='Foto de Perfil')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo Electrónico')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=None, max_length=30, null=True, verbose_name='Sexo')),
                ('is_active', models.BooleanField(default=True)),
                ('date_entry', models.DateField(help_text='Fecha de ingreso de empleado', verbose_name='Fecha de Ingreso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Se unió el')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to='employees.employee', verbose_name='Usuario creador')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to='employees.employee')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ('created_at',),
            },
        ),
    ]
