# Generated by Django 4.2 on 2025-07-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_area_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code_afp',
            field=models.CharField(max_length=200, null=True, verbose_name='Código de AFP'),
        ),
        migrations.AddField(
            model_name='employee',
            name='type_pension',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Tipo de pensión'),
        ),
    ]
