# Generated by Django 4.2 on 2025-07-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_code_afp_employee_type_pension'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Hijos?'),
        ),
    ]
